version: '2'

services:
  app:
    image: spoon4/goprince:0.1
    command: make --no-print-directory run
    volumes:
      - ./src/goprince:/workspace/src/goprince
      - ./public:/public
    environment:
      APP_ENV: dev
    ports:
      - "8080:8080"
    logging:
      driver: 'json-file'